# Top of file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/sulimusa/circleci-hello
    steps:
      - checkout # Checks out the source code
      - run: echo "Hello World!"
